language: python
python:
- '2.7'
addons:
  apt:
    packages:
      - pandoc
install: pip install -r requirements-dev.txt
script: nosetests
deploy:
  provider: pypi
  user: rjosephwright
  password:
    secure: QZcHROovcp0fRUwrlBhB9wBZm0GxwRhNW4i7Xk5tneWmw0Lvp4ttMBrgrVZVQSvdMOGObxFIu1fynvv1HfwR5NNyP/Fw/QvCiL+vaOW0MR8zpaCtLFkaQSM9qk418F4xOF0smGIEoYdh6PtL3P5JAskZWwmdlyaMeGNhVYvSYWhJkyKGZ9GrBixxOEOIF5HCzFw9rp8zrDfEZB3/QuisIQRB7mqTFN0ePEUlPI9VJrrbtcKbP+HKm+eS7SdyfTT4NKqfPbbb3wOnyFAVsi9uPn3lT0VLg+/deFHJcnCBoaWqMGDXXJmxqFh59U8h+O+PXHK2+0D6+YoO26TwigdyxLnaSh3sE2j4rln6SP2h+eSOUelm80N9EegB/ArYu3WKxTV5CL8pAKxFb7nxgHEvlCoN7KsEMF9v8Mdu+qv0ux1OE3D9UEixDALTO2rJ8izG0imLjoy6WSgf5h75dl8s6bHQepk+YcNDiFE7JRMEIDdqq9C/Q3qmq5/U1sgcH2OWCENmTQwSkXMpI4P/ZpKKDBRSIvcMx92VbucPnHFjzRBQkOEBXyVmNO0d5Q21stcL0VXWv+ecZMGQugDIDvIjTDvDu91sfWEbg1tkKtzdvyLPbn8W/WOUMoNvbSeT1Upk+J1pJeSq60xM6DyUHLqHDehGh5iAQYBOMykdHycQCOY=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: cloudboss/bossimage
