language: python
python:
- '2.7'
addons:
  apt:
    packages:
      - pandoc
install: pip install -r requirements-dev.txt
script: nosetests
deploy:
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: rjosephwright
    password:
      secure: PzxSgIMizOiOtBErXkHrF4fb7sSiYvLtT98U41T+esdWmWhHwAYUoWDViqP8AooTXSd+Kovk9M4uj2GpnCTIRfHwUOj2UlZQxFQKrCg0VV582KSOX3RUFiIlVtvQB65ykA+xJizS7gdGmddZIN/yUZLY6qzS/HYlEGvPqeJpPOA/IdR++K8PxTomjNl+CKCxFxcrKl2+SBrNZ+fn2KqJ+P6yz0RM5j31/KHw6fNgB2tTGaYzeIfVCKKuBPsF33bXMk/RG9P+izjGapCNhvC+FXTxrMnv1ilKy7kp1h7hGBLp+rivX1A9bkR6w6nLYulUuS7V6hGSVA/ZIXK7WfDLT3X1shAdXNdbZUyWWMrnuivBFCNK24UqnyG4032idDbwBPUdfY1/FawVbNeV9d57W7ZjMeco78OBY2e3gViRuOfoo8mpCE9ZhVa6aoa5IcoQYBPyMJI8ZWgRVrsXjm4r/+uaqeKrB46/Ix8elySc2NEvHVLid3+O+SMFWQayI3XFBe4M+eLoBQo5FRq28nZAAQozJLiaO9DFXMaw1YDMRzoUii/9Ik8FdiqIlGFR603rUTiWL5ah9m3+WYpLsF1CnkGj9hEBqYcFZOau+Z7B2rp9COEndJHEKCU4jgyjodOi3iqwg52Wp02L59u4UT83sMVmsq3/271R14UeMZLX/bg=
    on:
      tags: false
      distributions: sdist bdist_wheel
      repo: cloudboss/bossimage
  - provider: pypi
    user: rjosephwright
    password:
      secure: qaIcano/+hH0v38pHy5Isz6zJsvjnyK3Ou+i0Pwpe2sVESxSaDUnk5leeEMzw+rX4FTBmNaZ7BOoGeeS2dW0qLC7ifPnXUt5ibuzV0LdfubeC51kHNNZh6cAiNvq39y55HNQlTRyNmJLpIJS/Otd2hrWUkiNnSxqtWFOaHrr+LnbIMLLQeaowTZXVg2qJdkcyS8vEwcOE3vlA1/u6UbWRTu/LHgvkClycvTi1gMwdDbw6f7MQUu+7Gx9iKjUWzqgf8MrPUW6qGzB9mef8uH9V970hJiuF4jlzltHDJlHfis04UsL4uI24lNFnJWW708JmHCknLfPpE1EIFdAw4hYb12SbCQt+VCz0MWBuSXBUqNwGQgpZTfA7CTl6TIl++hLFABhhnCfk3u2ZyqtTlw5vWIwJ0mhJjk8u1fquOpR+asEi1/brffE3+SXjbQm6Rhd2RI3XZMMuaAtkW5Oz2rXHktJp2DgvojGfOsn6p1hd6MrRa4ECcudyMwMWW346iicrpVhkWlUc2Mw9/QpObDIQpyWWchX0E+tYHSLMD/UZ898WsCz/jqpowxRM8QxtVs9JfuZPmAT41Qrpehh5h37u57IlHEQ3mFJyKxnwsvKz4tWi1YEHExPDkc4D+LT8ECSp8zmsq2B8LJDEa02rEOjQrUOO3lRcV83cfujJtKxoiU=
    on:
      tags: true
      distributions: sdist bdist_wheel
      repo: cloudboss/bossimage
